export const COLORS = {
    light: {
        background: "#F3F2E9",
        foreground: "#1E3D2F",
        card: "#FFFFFF",
        cardForeground: "#1E3D2F",
        popover: "#FFFFFF",
        popoverForeground: "#1E3D2F",
        primary: "#1E3D2F",
        primaryForeground: "#FFFFFF",
        secondary: "#A3B18A",
        secondaryForeground: "#1E3D2F",
        muted: "#EAE8DC",
        mutedForeground: "#5C6B63",
        accent: "#FF6B4A",
        accentForeground: "#FFFFFF",
        destructive: "#EF4444",
        destructiveForeground: "#FFFFFF",
        border: "#D4D4C8",
        input: "#EAE8DC",
        ring: "#FF6B4A",
        warning: "#FDB913",
        warningForeground: "#000000",
    },
    dark: {
        background: "#0A0A0A",
        foreground: "#FAFAFA",
        card: "#171717",
        cardForeground: "#FAFAFA",
        popover: "#171717",
        popoverForeground: "#FAFAFA",
        primary: "#FF6B6B",
        primaryForeground: "#FFFFFF",
        secondary: "#4ECDC4",
        secondaryForeground: "#FFFFFF",
        muted: "#262626",
        mutedForeground: "#A3A3A3",
        accent: "#FF8243",
        accentForeground: "#FFFFFF",
        destructive: "#EF4444",
        destructiveForeground: "#FFFFFF",
        border: "#333333",
        input: "#333333",
        ring: "#FF6B6B",
        warning: "#FDB913",
        warningForeground: "#000000",
    },
};
